name: leveldb-master-pipeline
on:
  push:
    branches:
      - master

jobs:
  golang_lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Install GO
        uses: actions/setup-go@v3
        with:
          go-version: 1.15
          check-latest: true

      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Format Code
        run: gofmt
        
      - name: golang-lint
        run: |
            go get -u golang.org/x/lint/golint
            golint ./...

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Install GO
        uses: actions/setup-go@v3
        with: 
          go-version: 1.15
          check-latest: true
          cache: true

      - name: Verify Dependencies
        run: |
            go mod verify
            go mod tidy
            
      - name: Create Storage for Build-Binary
        run: mkdir -p ~/artifacts

      - name: Build
        run: go build -o ~/artifacts/ -v ./...
        
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          path: ~/artifacts
  
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Install GO
        uses: actions/setup-go@v3
        with: 
          go-version: 1.15
          check-latest: true
          cache: true

      - name: Verify Dependencies
        run: |
            go mod verify
            go mod tidy

      - name: Unit Test
        run: go test -timeout 30m -race -run "TestDB_(Concurrent|GoleveldbIssue74)" ./leveldb
