name: leveldb-stag-pipeline
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Install GO
        uses: actions/setup-go@v3
        with: 
          go-version: 1.15
          cache: true

      - name: Verify Dependencies
        run: |
            go mod verify
            go mod tidy

      - name: Build
        run: go build -v ./...

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Install GO
        uses: actions/setup-go@v3
        with: 
          go-version: 1.15
          cache: true

      - name: Verify Dependencies
        run: |
            go mod verify
            go mod tidy

      - name: Unit Test
        run: go test -v -race ./...

  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Install GO
        uses: actions/setup-go@v3
        with: 
          go-version: 1.15

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --verbose
